name: Checkout and List Files

on: [push]

jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List repository files
        run: ls -la
