name: Using Secrets

on: [push]

jobs:
  secret_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret (not recommended in production)
        run: echo "The secret key is ${{ secrets.MY_SECRET }}"
